In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 101, size=5)

In [3]:
print(arr)

[95 23 43 64 25]


In [4]:
arr1 = np.arange(1, 11)

In [6]:
reshaped_arr = arr1.reshape(2, 5)

In [7]:
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
arr2 = np.arange(1, 21)

In [10]:
extracted_arr = arr[4:15]

In [11]:
print(extracted_arr)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [13]:
arr3 = np.linspace(0, 1, num=10)

In [14]:
print(arr3)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [15]:
arr4 = np.arange(1, 10)

In [17]:
squared_arr = np.square(arr4)

In [18]:
print(squared_arr)

[ 1  4  9 16 25 36 49 64 81]
